/* 
 * FastStats API
 *
 * An API to allow access to FastStats resources
 *
 * OpenAPI spec version: v2
 * Contact: support@apteco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Apteco.OrbitSlackBot.ApiClient.Client.SwaggerDateConverter;

namespace Apteco.OrbitSlackBot.ApiClient.Model
{
    /// <summary>
    /// Details for registering a collection hit
    /// </summary>
    [DataContract]
    public partial class CreateCollectionHitDetails :  IEquatable<CreateCollectionHitDetails>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCollectionHitDetails" /> class.
        /// </summary>
        /// <param name="UserAgentDetails">Details of the client application that made the view.</param>
        public CreateCollectionHitDetails(string UserAgentDetails = default(string))
        {
            this.UserAgentDetails = UserAgentDetails;
        }
        
        /// <summary>
        /// Details of the client application that made the view
        /// </summary>
        /// <value>Details of the client application that made the view</value>
        [DataMember(Name="userAgentDetails", EmitDefaultValue=false)]
        public string UserAgentDetails { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateCollectionHitDetails {\n");
            sb.Append("  UserAgentDetails: ").Append(UserAgentDetails).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateCollectionHitDetails);
        }

        /// <summary>
        /// Returns true if CreateCollectionHitDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateCollectionHitDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateCollectionHitDetails input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.UserAgentDetails == input.UserAgentDetails ||
                    (this.UserAgentDetails != null &&
                    this.UserAgentDetails.Equals(input.UserAgentDetails))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.UserAgentDetails != null)
                    hashCode = hashCode * 59 + this.UserAgentDetails.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
