/* 
 * FastStats API
 *
 * An API to allow access to FastStats resources
 *
 * OpenAPI spec version: v2
 * Contact: support@apteco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Apteco.OrbitSlackBot.ApiClient.Client.SwaggerDateConverter;

namespace Apteco.OrbitSlackBot.ApiClient.Model
{
    /// <summary>
    /// Details used to modify a collection for a given user
    /// </summary>
    [DataContract]
    public partial class ModifyUserCollection :  IEquatable<ModifyUserCollection>, IValidatableObject
    {
        /// <summary>
        /// The type of modification to perform.  If the type is delete or undelete, any other specified item details will be ignored
        /// </summary>
        /// <value>The type of modification to perform.  If the type is delete or undelete, any other specified item details will be ignored</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ModificationTypeEnum
        {
            
            /// <summary>
            /// Enum Modify for value: Modify
            /// </summary>
            [EnumMember(Value = "Modify")]
            Modify = 1,
            
            /// <summary>
            /// Enum Delete for value: Delete
            /// </summary>
            [EnumMember(Value = "Delete")]
            Delete = 2,
            
            /// <summary>
            /// Enum Undelete for value: Undelete
            /// </summary>
            [EnumMember(Value = "Undelete")]
            Undelete = 3
        }

        /// <summary>
        /// The type of modification to perform.  If the type is delete or undelete, any other specified item details will be ignored
        /// </summary>
        /// <value>The type of modification to perform.  If the type is delete or undelete, any other specified item details will be ignored</value>
        [DataMember(Name="modificationType", EmitDefaultValue=false)]
        public ModificationTypeEnum ModificationType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ModifyUserCollection" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ModifyUserCollection() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ModifyUserCollection" /> class.
        /// </summary>
        /// <param name="Collection">The collection to modify (required).</param>
        /// <param name="Id">The id of the item to update (required).</param>
        /// <param name="ModificationType">The type of modification to perform.  If the type is delete or undelete, any other specified item details will be ignored (required).</param>
        public ModifyUserCollection(ModifyUserCollectionDetail Collection = default(ModifyUserCollectionDetail), int? Id = default(int?), ModificationTypeEnum ModificationType = default(ModificationTypeEnum))
        {
            // to ensure "Collection" is required (not null)
            if (Collection == null)
            {
                throw new InvalidDataException("Collection is a required property for ModifyUserCollection and cannot be null");
            }
            else
            {
                this.Collection = Collection;
            }
            // to ensure "Id" is required (not null)
            if (Id == null)
            {
                throw new InvalidDataException("Id is a required property for ModifyUserCollection and cannot be null");
            }
            else
            {
                this.Id = Id;
            }
            // to ensure "ModificationType" is required (not null)
            if (ModificationType == null)
            {
                throw new InvalidDataException("ModificationType is a required property for ModifyUserCollection and cannot be null");
            }
            else
            {
                this.ModificationType = ModificationType;
            }
        }
        
        /// <summary>
        /// The collection to modify
        /// </summary>
        /// <value>The collection to modify</value>
        [DataMember(Name="collection", EmitDefaultValue=false)]
        public ModifyUserCollectionDetail Collection { get; set; }

        /// <summary>
        /// The id of the item to update
        /// </summary>
        /// <value>The id of the item to update</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ModifyUserCollection {\n");
            sb.Append("  Collection: ").Append(Collection).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ModificationType: ").Append(ModificationType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ModifyUserCollection);
        }

        /// <summary>
        /// Returns true if ModifyUserCollection instances are equal
        /// </summary>
        /// <param name="input">Instance of ModifyUserCollection to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ModifyUserCollection input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Collection == input.Collection ||
                    (this.Collection != null &&
                    this.Collection.Equals(input.Collection))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.ModificationType == input.ModificationType ||
                    (this.ModificationType != null &&
                    this.ModificationType.Equals(input.ModificationType))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Collection != null)
                    hashCode = hashCode * 59 + this.Collection.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.ModificationType != null)
                    hashCode = hashCode * 59 + this.ModificationType.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
