/* 
 * FastStats API
 *
 * An API to allow access to FastStats resources
 *
 * OpenAPI spec version: v2
 * Contact: support@apteco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Apteco.OrbitSlackBot.ApiClient.Client.SwaggerDateConverter;

namespace Apteco.OrbitSlackBot.ApiClient.Model
{
    /// <summary>
    /// Details for a job to refresh the render data
    /// </summary>
    [DataContract]
    public partial class RenderDataRefreshJobDetail :  IEquatable<RenderDataRefreshJobDetail>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RenderDataRefreshJobDetail" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RenderDataRefreshJobDetail() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RenderDataRefreshJobDetail" /> class.
        /// </summary>
        /// <param name="Id">The job&#39;s id (required).</param>
        /// <param name="IsComplete">Whether the job is complete or not (required).</param>
        public RenderDataRefreshJobDetail(int? Id = default(int?), bool? IsComplete = default(bool?))
        {
            // to ensure "Id" is required (not null)
            if (Id == null)
            {
                throw new InvalidDataException("Id is a required property for RenderDataRefreshJobDetail and cannot be null");
            }
            else
            {
                this.Id = Id;
            }
            // to ensure "IsComplete" is required (not null)
            if (IsComplete == null)
            {
                throw new InvalidDataException("IsComplete is a required property for RenderDataRefreshJobDetail and cannot be null");
            }
            else
            {
                this.IsComplete = IsComplete;
            }
        }
        
        /// <summary>
        /// The job&#39;s id
        /// </summary>
        /// <value>The job&#39;s id</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// Whether the job is complete or not
        /// </summary>
        /// <value>Whether the job is complete or not</value>
        [DataMember(Name="isComplete", EmitDefaultValue=false)]
        public bool? IsComplete { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RenderDataRefreshJobDetail {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  IsComplete: ").Append(IsComplete).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RenderDataRefreshJobDetail);
        }

        /// <summary>
        /// Returns true if RenderDataRefreshJobDetail instances are equal
        /// </summary>
        /// <param name="input">Instance of RenderDataRefreshJobDetail to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RenderDataRefreshJobDetail input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.IsComplete == input.IsComplete ||
                    (this.IsComplete != null &&
                    this.IsComplete.Equals(input.IsComplete))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.IsComplete != null)
                    hashCode = hashCode * 59 + this.IsComplete.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
