/* 
 * FastStats API
 *
 * An API to allow access to FastStats resources
 *
 * OpenAPI spec version: v2
 * Contact: support@apteco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Apteco.OrbitSlackBot.ApiClient.Client.SwaggerDateConverter;

namespace Apteco.OrbitSlackBot.ApiClient.Model
{
    /// <summary>
    /// Details of the association between a label and a collection for a user
    /// </summary>
    [DataContract]
    public partial class UserCollectionLabelAssociationDetails :  IEquatable<UserCollectionLabelAssociationDetails>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserCollectionLabelAssociationDetails" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UserCollectionLabelAssociationDetails() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserCollectionLabelAssociationDetails" /> class.
        /// </summary>
        /// <param name="CollectionId">The id of the collection the label is associated with (required).</param>
        /// <param name="Id">The id of the label (required).</param>
        /// <param name="Description">The text for the label (required).</param>
        public UserCollectionLabelAssociationDetails(string CollectionId = default(string), int? Id = default(int?), string Description = default(string))
        {
            // to ensure "CollectionId" is required (not null)
            if (CollectionId == null)
            {
                throw new InvalidDataException("CollectionId is a required property for UserCollectionLabelAssociationDetails and cannot be null");
            }
            else
            {
                this.CollectionId = CollectionId;
            }
            // to ensure "Id" is required (not null)
            if (Id == null)
            {
                throw new InvalidDataException("Id is a required property for UserCollectionLabelAssociationDetails and cannot be null");
            }
            else
            {
                this.Id = Id;
            }
            // to ensure "Description" is required (not null)
            if (Description == null)
            {
                throw new InvalidDataException("Description is a required property for UserCollectionLabelAssociationDetails and cannot be null");
            }
            else
            {
                this.Description = Description;
            }
        }
        
        /// <summary>
        /// The id of the collection the label is associated with
        /// </summary>
        /// <value>The id of the collection the label is associated with</value>
        [DataMember(Name="collectionId", EmitDefaultValue=false)]
        public string CollectionId { get; set; }

        /// <summary>
        /// The id of the label
        /// </summary>
        /// <value>The id of the label</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// The text for the label
        /// </summary>
        /// <value>The text for the label</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserCollectionLabelAssociationDetails {\n");
            sb.Append("  CollectionId: ").Append(CollectionId).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UserCollectionLabelAssociationDetails);
        }

        /// <summary>
        /// Returns true if UserCollectionLabelAssociationDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of UserCollectionLabelAssociationDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserCollectionLabelAssociationDetails input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CollectionId == input.CollectionId ||
                    (this.CollectionId != null &&
                    this.CollectionId.Equals(input.CollectionId))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CollectionId != null)
                    hashCode = hashCode * 59 + this.CollectionId.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
